/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : twrk60d100m-pin
**     Processor   : MK60DN512VMD10
**     Component   : PinSettings
**     Version     : Component 01.007, Driver 1.2, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-06-08, 20:07, # CodeGen: 9
**     Abstract    :
**
**     Settings    :
**
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.2
** @brief
**
*/
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/

/* MODULE pin_mux. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"



void configure_can_pins(uint32_t instance)
{
  switch(instance) {
    case HW_CAN0:                       /* CAN0 */
      /* Affects PORTB_PCR19 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,19u,kPortMuxAlt2);
      /* Affects PORTB_PCR18 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,18u,kPortMuxAlt2);
      break;
    case HW_CAN1:                       /* CAN1 */
      /* Affects PORTE_PCR25 register */
      PORT_HAL_SetMuxMode(PORTE_BASE,25u,kPortMuxAlt2);
      /* Affects PORTE_PCR24 register */
      PORT_HAL_SetMuxMode(PORTE_BASE,24u,kPortMuxAlt2);
      break;
    default:
      break;
  }
}

void configure_enet_pins(uint32_t instance)
{
  /* Affects PORTA_PCR12 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,12u,kPortMuxAlt4);
  /* Affects PORTA_PCR13 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,13u,kPortMuxAlt4);
  /* Affects PORTA_PCR14 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,14u,kPortMuxAlt4);
  /* Affects PORTA_PCR15 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,15u,kPortMuxAlt4);
  /* Affects PORTA_PCR16 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,16u,kPortMuxAlt4);
  /* Affects PORTA_PCR17 register */
  PORT_HAL_SetMuxMode(PORTA_BASE,17u,kPortMuxAlt4);
  /* Affects PORTB_PCR0 register */
  PORT_HAL_SetMuxMode(PORTB_BASE,0u,kPortMuxAlt4);
  PORT_HAL_SetOpenDrainCmd(PORTB_BASE,0u,true);
  /* Affects PORTB_PCR1 register */
  PORT_HAL_SetMuxMode(PORTB_BASE,1u,kPortMuxAlt4);
}

void configure_gpio_pins(uint32_t instance)
{
  switch(instance) {
    case HW_PORTA:                      /* HW_PORTA */
      /* Affects PORTA_PCR19 register */
      PORT_HAL_SetPassiveFilterCmd(PORTA_BASE,19u,false);
      PORT_HAL_SetMuxMode(PORTA_BASE,19u,kPortMuxAsGpio);
      PORT_HAL_SetPullMode(PORTA_BASE,19u,kPortPullUp);
      PORT_HAL_SetPullCmd(PORTA_BASE,19u,true);
      /* Affects PORTA_PCR10 register */
      PORT_HAL_SetDriveStrengthMode(PORTA_BASE,10u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTA_BASE,10u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTA_BASE,10u,kPortSlowSlewRate);
      /* Affects PORTA_PCR11 register */
      PORT_HAL_SetDriveStrengthMode(PORTA_BASE,11u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTA_BASE,11u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTA_BASE,11u,kPortSlowSlewRate);
      /* Affects PORTA_PCR28 register */
      PORT_HAL_SetDriveStrengthMode(PORTA_BASE,28u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTA_BASE,28u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTA_BASE,28u,kPortSlowSlewRate);
      /* Affects PORTA_PCR29 register */
      PORT_HAL_SetDriveStrengthMode(PORTA_BASE,29u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTA_BASE,29u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTA_BASE,29u,kPortSlowSlewRate);
      break;
    case HW_PORTB:                      /* HW_PORTB */
      break;
    case HW_PORTC:                      /* HW_PORTC */
      break;
    case HW_PORTD:
      PORT_HAL_SetPassiveFilterCmd(PORTD_BASE, 10u, false);
      PORT_HAL_SetMuxMode(PORTD_BASE, 10u, kPortMuxAsGpio);
      break;
    case HW_PORTE:                      /* HW_PORTE */
      /* Affects PORTE_PCR26 register */
      PORT_HAL_SetPassiveFilterCmd(PORTE_BASE,26u,false);
      PORT_HAL_SetMuxMode(PORTE_BASE,26u,kPortMuxAsGpio);
      PORT_HAL_SetPullMode(PORTE_BASE,26u,kPortPullUp);
      PORT_HAL_SetPullCmd(PORTE_BASE,26u,true);
      /* Affects PORTE_PCR28 register */
      PORT_HAL_SetMuxMode(PORTE_BASE,28u,kPortMuxAsGpio);
      break;
    default:
      break;
  }
}

void configure_i2c_pins(uint32_t instance)
{
  switch(instance) {
    case HW_I2C0:                       /* I2C0 */
      /* Affects PORTD_PCR8 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,8u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTD_BASE,8u,true);
      /* Affects PORTD_PCR9 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,9u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTD_BASE,9u,true);
      break;
    case HW_I2C1:                       /* I2C1 */
      /* Affects PORTC_PCR10 register */
      PORT_HAL_SetMuxMode(PORTC_BASE,10u,kPortMuxAlt2);
      PORT_HAL_SetPullCmd(PORTC_BASE, 10u, true);
      PORT_HAL_SetPullMode(PORTC_BASE,10u,kPortPullUp);
      PORT_HAL_SetPassiveFilterCmd(PORTC_BASE, 10u, false);
      /* Affects PORTC_PCR11 register */
      PORT_HAL_SetMuxMode(PORTC_BASE,11u,kPortMuxAlt2);
      PORT_HAL_SetPullCmd(PORTC_BASE, 11u, true);
      PORT_HAL_SetPullMode(PORTC_BASE,11u,kPortPullUp);
      PORT_HAL_SetPassiveFilterCmd(PORTC_BASE, 11u, false);
      break;
    default:
      break;
  }
}

void configure_i2s_pins(uint32_t instance)
{
  /* Affects PORTE_PCR6 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,6u,kPortMuxAlt4);
  /* Affects PORTE_PCR7 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,7u,kPortMuxAlt4);
  /* Affects PORTE_PCR12 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,12u,kPortMuxAlt4);
  /* Affects PORTE_PCR11 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,11u,kPortMuxAlt4);
  /* Affects PORTE_PCR10 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,10u,kPortMuxAlt4);
}

void configure_rtc_pins(uint32_t instance)
{
  /* Affects PORTE_PCR26 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,26u,kPortMuxAlt6);
}

void configure_sdhc_pins(uint32_t instance)
{
  /* Affects PORTE_PCR3 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,3u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,3u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,3u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,3u,kPortHighDriveStrength);
  /* Affects PORTE_PCR1 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,1u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,1u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,1u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,1u,kPortHighDriveStrength);
  /* Affects PORTE_PCR0 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,0u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,0u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,0u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,0u,kPortHighDriveStrength);
  /* Affects PORTE_PCR5 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,5u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,5u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,5u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,5u,kPortHighDriveStrength);
  /* Affects PORTE_PCR4 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,4u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,4u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,4u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,4u,kPortHighDriveStrength);
  /* Affects PORTE_PCR2 register */
  PORT_HAL_SetMuxMode(PORTE_BASE,2u,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE_BASE,2u,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE_BASE,2u,true);
  PORT_HAL_SetDriveStrengthMode(PORTE_BASE,2u,kPortHighDriveStrength);
}

void configure_spi_pins(uint32_t instance)
{
  switch(instance) {
    case HW_SPI0:                       /* SPI0 */
      /* Affects PORTD_PCR0 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,0u,kPortMuxAlt2);
      /* Affects PORTD_PCR3 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,3u,kPortMuxAlt2);
      /* Affects PORTD_PCR1 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,1u,kPortMuxAlt2);
      /* Affects PORTD_PCR2 register */
      PORT_HAL_SetMuxMode(PORTD_BASE,2u,kPortMuxAlt2);
      break;
    case HW_SPI1:                       /* SPI1 */
      /* Affects PORTB_PCR10 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,10u,kPortMuxAlt2);
      /* Affects PORTB_PCR17 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,17u,kPortMuxAlt2);
      /* Affects PORTB_PCR11 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,11u,kPortMuxAlt2);
      /* Affects PORTB_PCR16 register */
      PORT_HAL_SetMuxMode(PORTB_BASE,16u,kPortMuxAlt2);
      break;
    case HW_SPI2:                       /* SPI2 */
      /* Affects PORTD_PCR12 register SCK */
      PORT_HAL_SetMuxMode(PORTD_BASE,12u,kPortMuxAlt2);
      /* Affects PORTD_PCR13 register MOSI */
      PORT_HAL_SetMuxMode(PORTD_BASE,13u,kPortMuxAlt2);
      /* Affects PORTD_PCR14 register MISO */
      PORT_HAL_SetMuxMode(PORTD_BASE,14u,kPortMuxAlt2);
      /* Affects PORTD_PCR15 register PCS1 */
      PORT_HAL_SetMuxMode(PORTD_BASE,15u,kPortMuxAlt2);
      /* Affects PORTD_PCR11 register PCS0 */
      PORT_HAL_SetMuxMode(PORTD_BASE,11u,kPortMuxAlt2);
      break;
    default:
      break;
  }
}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {
    case HW_UART3:                        /* UART3 */
      /* Affects PORTC_PCR16 register */
      PORT_HAL_SetMuxMode(PORTC_BASE,16u,kPortMuxAlt3);
      /* Affects PORTC_PCR17 register */
      PORT_HAL_SetMuxMode(PORTC_BASE,17u,kPortMuxAlt3);
      break;
    case HW_UART5:                      /* UART5 */
      /* Affects PORTE_PCR9 register */
      PORT_HAL_SetMuxMode(PORTE_BASE,9u,kPortMuxAlt3);
      /* Affects PORTE_PCR8 register */
      PORT_HAL_SetMuxMode(PORTE_BASE,8u,kPortMuxAlt3);
      break;
    default:
      break;
  }
}

void configure_spi_cs0_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD_BASE,0u,kPortMuxAsGpio);
}

void configure_spi_cs1_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD_BASE,4u,kPortMuxAsGpio);
}

void configure_gpio_i2c_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD_BASE,8u,kPortMuxAsGpio);
  PORT_HAL_SetMuxMode(PORTD_BASE,9u,kPortMuxAsGpio);
}

/* Setup FTM pins to drive LED */
void configure_ftm_pins(uint32_t instance)
{
  switch(instance) {
    case HW_FTM2:                       /* FTM2 */
      /* Affects PORTA_PCR11 register (D7 - RED)*/
      PORT_HAL_SetDriveStrengthMode(PORTA_BASE,11u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTA_BASE,11u,kPortMuxAlt3);
      PORT_HAL_SetSlewRateMode(PORTA_BASE,11u,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}
/* Setup TSI pins for on board electrodes */
void configure_tsi_pins(uint32_t instance) // todo
{
  switch(instance) {
    case 0:                             /* TSI0 */
      /* On Board Touch electrodes with LED's */
      /* PORTA_PCR4 */
      PORT_HAL_SetMuxMode(PORTA_BASE,4u,kPortPinDisabled);
      /* PORTB_PCR2 */
      PORT_HAL_SetMuxMode(PORTB_BASE,3u,kPortPinDisabled);
      /* PORTB_PCR3 */
      PORT_HAL_SetMuxMode(PORTB_BASE,2u,kPortPinDisabled);
      /* PORTB_PCR16 */
      PORT_HAL_SetMuxMode(PORTB_BASE,16u,kPortPinDisabled);
      
	  /* TWRPI TSI signals */
      /* PORTB_PCR0 */
      PORT_HAL_SetMuxMode(PORTB_BASE,0u,kPortPinDisabled);
      /* PORTB_PCR1 */
      PORT_HAL_SetMuxMode(PORTB_BASE,1u,kPortPinDisabled);
      /* PORTB_PCR2 */
      PORT_HAL_SetMuxMode(PORTB_BASE,2u,kPortPinDisabled);
      /* PORTB_PCR3 */
      PORT_HAL_SetMuxMode(PORTB_BASE,3u,kPortPinDisabled);
      /* PORTC_PCR0 */
      PORT_HAL_SetMuxMode(PORTC_BASE,0u,kPortPinDisabled);
      /* PORTC_PCR1 */
      PORT_HAL_SetMuxMode(PORTC_BASE,1u,kPortPinDisabled);
      /* PORTC_PCR2 */
      PORT_HAL_SetMuxMode(PORTC_BASE,2u,kPortPinDisabled);
      /* PORTA_PCR4 */
      PORT_HAL_SetMuxMode(PORTA_BASE,4u,kPortPinDisabled);
      /* PORTB_PCR16 */
      PORT_HAL_SetMuxMode(PORTB_BASE,16u,kPortPinDisabled);
      /* PORTB_PCR17 */
      PORT_HAL_SetMuxMode(PORTB_BASE,17u,kPortPinDisabled);
      /* PORTB_PCR18 */
      PORT_HAL_SetMuxMode(PORTB_BASE,18u,kPortPinDisabled);
      /* PORTB_PCR19 */
      PORT_HAL_SetMuxMode(PORTB_BASE,19u,kPortPinDisabled);
      break;
  default:
      break;
  }
}

void configure_cmp_pins(uint32_t instance)
{
    switch (instance)
    {
        case 0U:
            PORT_HAL_SetMuxMode(PORTC_BASE, 6U, kPortPinDisabled); /* PTC6 - CMP0_IN0. */
            break;
        default:
            break;
    }
}

/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.10]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
