<?xml version="1.0"?>
<workspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workingsets.xsd">
  <projects>
  <project><name>ksdk_platform_lib_K22F51212</name><path>../../../../../../lib/ksdk_platform_lib/kds/K22F51212</path><open>true</open><activeconfig>debug</activeconfig><buildreferences config="debug">false</buildreferences><activeconfig>release</activeconfig><buildreferences config="release">false</buildreferences></project><project><name>i2c_rtos_bm_slave_frdmk22f</name><path>.</path><open>true</open><activeconfig>debug</activeconfig><buildreferences config="debug">false</buildreferences><activeconfig>release</activeconfig><buildreferences config="release">false</buildreferences></project></projects>
  <workingsets>
  <workingSet editPageId="org.eclipse.cdt.ui.CElementWorkingSetPage" id="1323268527287_1" label="i2c_rtos_bm_slave" name="i2c_rtos_bm_slave"><item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/ksdk_platform_lib_K22F51212" type="4"/><item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/i2c_rtos_bm_slave_frdmk22f" type="4"/></workingSet></workingsets>
  <cdtconfigurations>
  <workingSet name="i2c_rtos_bm_slave"><config name="debug"><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="ksdk_platform_lib_K22F51212" configName="debug"/><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="i2c_rtos_bm_slave_frdmk22f" configName="debug"/></config><config name="release"><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="ksdk_platform_lib_K22F51212" configName="release"/><project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" name="i2c_rtos_bm_slave_frdmk22f" configName="release"/></config></workingSet></cdtconfigurations>
</workspace>
