/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : hardware_init.c
**     Project     : SDK
**     Processor   : MKV30F128VLH10
**     Component   : PinSettings
**     Version     : Component 01.002, Driver 1.1, CPU db: 3.00.000
**     Compiler    : IAR ARM C Compiler
**     Date/Time   : 02-07-2014, 10:25, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         GPIO                - void hardware_init_GPIO(uint32_t instance);
**         I2C                 - void hardware_init_I2C(uint32_t instance);
**         SPI                 - void hardware_init_SPI(uint32_t instance);
**         UART                - void hardware_init_UART(uint32_t instance);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file hardware_init.c
** @version 1.1
** @brief
**
*/
/*!
**  @addtogroup hardware_init_module hardware_init module documentation
**  @{
*/

/* MODULE hardware_init. */

//#include "fsl_platform_types.h"
#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "pin_mux.h"


void configure_gpio_pins(uint32_t instance)
{
  switch(instance) {
    case 0:                             /* PTA */
      /* PORTA_PCR4 */
      PORT_HAL_SetMuxMode(PORTA_BASE,4u,kPortMuxAsGpio);
      break;
    case 1:                             /* PTB */
      /* PORTB_PCR0 */
      PORT_HAL_SetMuxMode(PORTB_BASE,16u,kPortMuxAsGpio);
      /* PORTB_PCR1 */
      PORT_HAL_SetMuxMode(PORTB_BASE,17u,kPortMuxAsGpio);
      /* PORTB_PCR6 */
      PORT_HAL_SetMuxMode(PORTB_BASE,19u,kPortMuxAsGpio);
      break;
    case 2:                             /* PTC */
      /* PORTC_PCR6 */
      PORT_HAL_SetMuxMode(PORTC_BASE,6u,kPortMuxAsGpio);
      /* PORTC_PCR7 */
      PORT_HAL_SetMuxMode(PORTC_BASE,11u,kPortMuxAsGpio);
      break;
    case 3:                             /* PTD */
      /* PORTD_PCR0 */
      PORT_HAL_SetMuxMode(PORTD_BASE,0u,kPortMuxAsGpio);
      /* PORTD_PCR1 */
      PORT_HAL_SetMuxMode(PORTD_BASE,1u,kPortMuxAsGpio);
      /* PORTD_PCR4 */
      PORT_HAL_SetMuxMode(PORTD_BASE,4u,kPortMuxAsGpio);
      /* PORTD_PCR7 */
      PORT_HAL_SetMuxMode(PORTD_BASE,7u,kPortMuxAsGpio);
      break;
    case 4:                             /* PTE */
      /* PORTE_PCR0 */
      PORT_HAL_SetMuxMode(PORTE_BASE,0u,kPortMuxAsGpio);
      /* PORTE_PCR1 */
      PORT_HAL_SetMuxMode(PORTE_BASE,1u,kPortMuxAsGpio);
      /* PORTE_PCR24 */
      PORT_HAL_SetMuxMode(PORTE_BASE,24u,kPortMuxAsGpio);
      /* PORTE_PCR25 */
      PORT_HAL_SetMuxMode(PORTE_BASE,25u,kPortMuxAsGpio);
      break;
    default:
      break;
  }
}

void configure_i2c_pins(uint32_t instance)
{
  switch(instance) {
    case 0:                           /* I2C0_TWR ELEVATOR_OUTPUT*/
      /* PORTD_PCR2 */
      PORT_HAL_SetMuxMode(PORTD_BASE,2u,kPortMuxAlt7);/*I2C0_SCL_ELEV*/
      PORT_HAL_SetOpenDrainCmd(PORTD_BASE,2u,true);
      /* PORTD_PCR3 */
      PORT_HAL_SetMuxMode(PORTD_BASE,3u,kPortMuxAlt7);/*2C0_SDA_ELEV*/
      PORT_HAL_SetOpenDrainCmd(PORTD_BASE,3u,true);
      break;

    default:
      break;
  }
}
void configure_spi_pins(uint32_t instance)
{
  switch(instance) {
    case 0:                             /* SPI0 */
      /* PORTE_PCR16 */
      PORT_HAL_SetMuxMode(PORTE_BASE,16u,kPortMuxAlt2);/*SPI0_CS0*/
      /* PORTE_PCR17 */
      PORT_HAL_SetMuxMode(PORTE_BASE,17u,kPortMuxAlt2);/*SPI0_SCK */
      /* PORTE_PCR18 */
      PORT_HAL_SetMuxMode(PORTE_BASE,18u,kPortMuxAlt2);/*SPI0_MOSI*/
      /* PORTE_PCR19 */
      PORT_HAL_SetMuxMode(PORTE_BASE,19u,kPortMuxAlt2);/*SPI0_MISO*/
      break;
      /* SPI1 */
      /* Not supported, only have one SPI module*/
    default:
      break;
  }
}

void configure_spi_cs0_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTE_BASE,16u,kPortMuxAsGpio);
}

void configure_spi_cs1_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC_BASE,3u,kPortMuxAsGpio);
}

void configure_gpio_i2c_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD_BASE,2u,kPortMuxAsGpio);
  PORT_HAL_SetMuxMode(PORTD_BASE,3u,kPortMuxAsGpio);
}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {
    case 0:                             /* UART0 */
      /* PORTB_PCR16 */
      PORT_HAL_SetMuxMode(PORTB_BASE,16u,kPortMuxAlt3);
      /* PORTB_PCR17 */
      PORT_HAL_SetMuxMode(PORTB_BASE,17u,kPortMuxAlt3);
      break;
    default:
      break;
  }
}

/* Setup FTM pins to drive LEDs */
void configure_ftm_pins(uint32_t instance)
{
  switch(instance) {
    case 0:                             /*FTM0_CH1*/
    /* PORTD_PCR7 (D7 - Green) */
    PORT_HAL_SetMuxMode(PORTD_BASE, 7u, kPortMuxAlt4);
    break;
  case 1:                              /*FTM2_CH1*/
  case 2:
     /* PORTB_PCR19 (B19 - Orange) */
    PORT_HAL_SetMuxMode(PORTB_BASE, 19u, kPortMuxAlt3);
    break;
    default:
      break;
  }
}

/* END hardware_init. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
